language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: Kv+KyzYdi2qaX6/t/6Og37AVbujNavYf39Hr2em6KHoHs06OBbinKdkUx+djfvfcwEG3IlqshpnC/YvDFOVfsNm2wS7w0EIXEgmI4PAeFiZC0V+VQP6r77AX7/ZeM2iFwNodgHHgTsZbYbjmb3gOnkyV/BlrCUoeod2Fz0TDS8z4SSK1Ikr5gljlMlx7E3GQb1F8QOU+ouanlK5d6q/2rioXdkmQpbaFpBmEkq801kefV2Cnp9MhgVxg1GuuUqDiSoLyDO5j/lSmKW8RurYXJE8JmjNf5OYe2e1yUoR7TXccQ7OZNPV0/tOMNiSUijcKvDEiUwMYk1A9UYWppHH76Yo4dtttGoEPXJ3I1OLIg0PYROmPA4kqdANq1/qFLvlm7SPRkWIBUbmSZ8S3+ByLQzvwLrzW2NDTF8x1N4NFQuzLxq3P2eh+kaXrEJuiYdZBIi5LRMCDGIBPPJWikv9+vhGuIkepupbuUhdlBJzM5fR/1t9b3/OPc9yXdhb8w1z727PJu9MgyKgmUtb/KLWHJp2qbBNNHKrU93tOqOe8askOLQGrAJNyYGejtPsImcXTPp2Le7TkzeWjyYB2mkx/Vl+i1FYdvEkOGkHDV5r3Vpmgl0L44aON+yEveOjNZ578UikrMTWb2pBKCIM5way+cr2ivRhW1DElzLbcArGdR5o=
  app: frozen-earth-10719
  on:
    repo: raysmithdev/full-stack-app-demo-server
